"""add_cv_metadata_fields

Revision ID: bf10ee4875d2
Revises: 016
Create Date: 2026-09-06 16:38:13.593841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf10ee4875d2'
down_revision: Union[str, None] = '016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('is_validated', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('resumes', sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('resumes', sa.Column('parsed_industry', sa.String(length=100), nullable=True))
    op.add_column('resumes', sa.Column('desired_role', sa.String(length=255), nullable=True))
    op.add_column('resumes', sa.Column('desired_location', sa.String(length=255), nullable=True))
    op.add_column('resumes', sa.Column('parsed_experience_level', sa.String(length=20), nullable=True))
    op.add_column('resumes', sa.Column('parsed_key_skills', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('industry_category_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_resumes_industry_category_id'), 'resumes', ['industry_category_id'], unique=False)
    op.create_index(op.f('ix_resumes_parsed_experience_level'), 'resumes', ['parsed_experience_level'], unique=False)
    op.create_index(op.f('ix_resumes_parsed_industry'), 'resumes', ['parsed_industry'], unique=False)
    op.create_foreign_key(None, 'resumes', 'job_categories', ['industry_category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.drop_index(op.f('ix_resumes_parsed_industry'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_parsed_experience_level'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_industry_category_id'), table_name='resumes')
    op.drop_column('resumes', 'industry_category_id')
    op.drop_column('resumes', 'parsed_key_skills')
    op.drop_column('resumes', 'parsed_experience_level')
    op.drop_column('resumes', 'desired_location')
    op.drop_column('resumes', 'desired_role')
    op.drop_column('resumes', 'parsed_industry')
    op.drop_column('resumes', 'validated_at')
    op.drop_column('resumes', 'is_validated')
    # ### end Alembic commands ###
